### PR TITLE
Check 101 (new) - Prefer IS NOT to NOT IS

### PR DESCRIPTION
**Pull request by AlexandreHT**
Second try (after PR 958) for test case (issue #722).
- master language English
- no extra text elements

### CODE REVIEW

**Comment by larshp** [comment]
https://github.com/abaplint/abaplint/issues/1098

**Comment by larshp** [comment]
okay, linter false positives fixed

see the 5 errors, https://github.com/larshp/abapOpenChecks/pull/959/checks

**Comment by AlexandreHT** [comment]
Corrected

**Comment by larshp** [comment]
👍

**Pull request merged**
