### PR TITLE
Check 103 - SELECT on table with replacement obj

### PR DESCRIPTION
**Pull request by fidley**
#1134

### CODE REVIEW

**Comment by larshp** [comment]
also add a document in this folder https://github.com/larshp/abapOpenChecks/tree/main/docs/_checks, it doesnt have to be much, just a few words on it

**Comment by fidley** [comment]
@larshp do you want to review additionally, or should I just merge?

**Comment by larshp** [comment]
looks good to me, so feel free to merge. But also we are in no hurry, so suggest leaving it open for a day or two, to let others have a look

**Comment by fidley** [comment]
Then I'll leave it here for some time.

**Pull request merged**
