### PR TITLE
 SY variable analyzer: Use statement index and add unit tests

### PR DESCRIPTION
**Pull request by ConjuringCoffee**
This makes using the result of the variable analyzer easier. Before this change, it wasn't possible to easily get the statement of the token.

Currently only relevant for check 102.

~EDIT: I extended this pull request to be about enabling the checksum for check 102 which requires the statement index from the variable analyzer.~

### CODE REVIEW

**Comment by larshp** [comment]
is it possible to add a unit test for this?

**Comment by ConjuringCoffee** [comment]
Hmm, `ZCL_AOC_SY_VARIABLE_ANALYZER` has a significant dependency to `ZCL_AOC_SCAN`. If the instantiation using code from `ZCL_AOC_UNIT_TEST` was encapsulated, then it would be possible to add unit tests directly for it. 

Currently, it is only indirectly covered by the tests from `ZCL_AOC_CHECK_102` (96% branch coverage).

**Comment by ConjuringCoffee** [comment]
Hmm, this isn't yet behaving how I intended it to. 

`p_position` seems to be intended for the statement index, but it's also used for calculating the checksum? The checksum should be calculated using the row number here.

Example:

```abap
IF sy-sysyid = 'TST'
OR sy-sysid = 'PRD'.
```

Doing the calculation with the statement index will use `1` for both checksum calculations, when we actually want `1` and then `2` instead. The easiest fix would be to supply `p_checksum_1` directly for this check. However, I suspect that the checksum calculation of other checks is faulty as well... so that should be analyzed.

**Comment by ConjuringCoffee** [comment]
I'm removing the checksum stuff from this pull request again. This seems to be a bigger topic and I shouldn't mix this here. I'm working on the unit tests now.

**Review by larshp — APPROVED** [review]
lgtm

**Pull request merged**
