### PR TITLE
Check String literals with LIKE, CP, NP - Issue #721

### PR DESCRIPTION
**Pull request by ibnbr**

### CODE REVIEW

**Comment by larshp** [comment]
Few `sy-subrc` checks missing, plus for this one we can add unit tests, see some of the other checks for examples

**Comment by larshp** [comment]
closes #721

**Comment by ibnbr** [comment]
Done.

**Comment by ibnbr** [comment]
I think this closes #29 too.

**Comment by larshp** [comment]
yea, thanks 👍

**Pull request merged**
