### PR TITLE
Addition of openssf scorecard badge and workflow 

### PR DESCRIPTION
**Pull request by andy778**
For more information look at https://securityscorecards.dev/

### CODE REVIEW

**Comment by larshp** [comment]
thanks, but no, closing

**Comment by andy778** [comment]
Fair, the reason for scorecard was security also, don't want to use software that is not maintained and configured right.. Better if you add your self

**Comment by larshp** [comment]
the scorecard setup could have been done in a way so it doesnt require each project to run actions

for "vulnerbilities" there are no checkers for ABAP

"dependency update tool", there are none for ABAP

"fuzzing", there are none for ABAP

everything around building, the project doesnt have builds

**Comment by andy778** [comment]
Looking at the output from the client side, and it's mostly critical and high I look on
E.g. 
- Branch-Protection is 3 today, so this could be better 
-  Security-Policy  0
- SAST, but I don't think it will find anything in this project ever...

**Pull request closed without merging**
