### PR TITLE
Added CLEAR WITH

### PR DESCRIPTION
**Pull request by MartinH1337**
The check for "CLEAR ... WITH" was added as permissible. In doing so, the condition according to "think positive" was reversed.

### CODE REVIEW

**Comment by larshp** [comment]
can you reduce the line length, as noted by abaplint, https://github.com/larshp/abapOpenChecks/pull/1061/checks?check_run_id=4984072786

**Comment by MartinH1337** [comment]
done.

**Comment by MartinH1337** [comment]
What do you think of an attribute allowing this CHECK x WITH y? Necessary? 
I have the code ready and tested, just because I wanted to try it out.

**Comment by larshp** [comment]
#1060

**Comment by larshp** [comment]
not nessesary, I think CLEAR WITH can be seen as an an assignment

**Comment by larshp** [comment]
thanks, welcome to abapOpenChecks as a contributor 🎉

**Comment by MartinH1337** [comment]
thanks a lot for your warm welcome. I am very excited as this is my first contribution to a github.

**Pull request merged**
