### PR TITLE
infinite loop fix

### PR DESCRIPTION
**Pull request by PShumilov**
infinite loop fix #1024 
There is infinite loop in method `remove_method_calls` caused by changing mt_tokens in method `replace`

### CODE REVIEW

**Comment by larshp** [comment]
cool, are all the unit tests okay? if I remember correctly there are some for this class 😁

**Comment by PShumilov** [comment]
> cool, are all the unit tests okay? if I remember correctly there are some for this class 😁

yeah, everething is OK 👍

**Comment by larshp** [comment]
thanks 👍 welcome to abapOpenChecks

**Comment by PShumilov** [comment]
Oh, thank you

**Pull request merged**
