### PR TITLE
New Check: Only Static Methods in one Class #758

### PR DESCRIPTION
**Pull request by ibnbr**

### CODE REVIEW

**Comment by larshp** [comment]
closes #758

**Comment by larshp** [comment]
the parser errors are due to a bug in abaplint 2.3.0, sec, fixing

**Comment by ibnbr** [comment]
Adjusted Pretty Printer

**Comment by larshp** [comment]
Thanks, few comments:

A: Suggest inheriting from ZCL_AOC_SUPER_ROOT instead, the other superclass will also parse the ABAP code which takes up performance
B: Please add documentation file to folder https://github.com/larshp/abapOpenChecks/tree/master/docs/_checks, see examples in the folder

**Pull request merged**
