### PR TITLE
Change Name of Check 69

### LINKED ISSUE #524: 69, change name to "Prefix naming conventions"
check 69, change name to "Prefix naming conventions"

### PR DESCRIPTION
**Pull request by DennstedtB**
resolves #524

### CODE REVIEW

**Comment by DennstedtB** [comment]
Intresting... did nothing in the testclasses mentioned in ABAPLint. - But I'll have a look over it.

**Comment by larshp** [comment]
new version of abaplint was released earlier, which takes this into account, move the && concat to a new statement before APPEND

https://github.com/abaplint/abaplint/issues/635

**Comment by g-back** [comment]
@DennstedtB please remember to use certain keywords, so the corresponding issue is automatically closed [(see link)](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords#about-issue-references), in this case something like "resolves #524"

**Comment by DennstedtB** [comment]
@g-back ah, thank you. Did not know this feature!

**Pull request merged**
