### PR TITLE
Added Check number 92 ( with docs )

### PR DESCRIPTION
**Pull request by DennstedtB**
Created abapOpenCheck Number 92 - I couldn't find anywhere if a unit test exists. Only if it is successfull. But if there is no unit test, SCI will accept this. This test should prevent this

### CODE REVIEW

**Comment by larshp** [comment]
see https://raw.githubusercontent.com/larshp/abapOpenChecks/master/docs/_checks/91.md for an example of the markdown the top part with the meta data is required for the https://docs.abapopenchecks.org/checks/ to render proplery

**Comment by DennstedtB** [comment]
Okay, now everything should be okay. ( I need to get used to abaplint ) 

Also added the metadata to the documentation

**Comment by larshp** [comment]
woah, this has original language = German? abapGit should have shown this as a warning?

**Comment by DennstedtB** [comment]
Hmm, there was no warning about this. I'll have a look at this the next time I commit something

**Pull request merged**
