### PR TITLE
Observe registered ATC namespaces

### PR DESCRIPTION
**Pull request by MiLiCLN**
In addition to Y/Z, also observe your own registered ATC namespaces.

### CODE REVIEW

**Comment by larshp** [comment]
Looking at the code, I guess the problem we are trying to solve is:

If a function group is in a registered customer namespace it is currently skipped, and we expect it to not be skipped.

?

**Comment by MiLiCLN** [comment]
As with the Y/Z namespace, the aim here must also be to exclude the includes (*/L*UXX) in the registered ATC namespace.
For example: Suppress pretty printer findings in those generated includes.

**Comment by MiLiCLN** [comment]
done

**Comment by larshp** [comment]
Thanks, welcome as a contributor 🎉

**Pull request merged**
