### PR TITLE
Number of WHENs in CASE

### PR DESCRIPTION
**Pull request by jwigert**
Issue #201 
I focused on CASE to begin with, and will do SWITCH a bit later.
I thought I'd create a separate PR for the documentation once I've gotten feedback on the code.

### CODE REVIEW

**Comment by jwigert** [comment]
I wasn't aware of the 702 limitations. I'll push an update a bit later.

**Comment by DennstedtB** [comment]
If you change your description to "resolves # 201" ( without the space ) then the issue will be closed if this pull request is merged [https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords)

**Comment by jwigert** [comment]
@DennstedtB Thanks, that's good to know. I'm not sure if I should do it in this specific case though. It depends on if we should put CASE and SWITCH in the same check, or if they should be two different checks. What do you think?

**Comment by jwigert** [comment]
I've fixed the 702 compatibility issues.

**Pull request merged**
