### PR TITLE
Check 101 - Predicates function & tables expression

### PR DESCRIPTION
**Pull request by AlexandreHT**
False-positive for predicates function & tables expression

### CODE REVIEW

**Comment by AlexandreHT** [comment]
Considering that :
* AOC requires 740sp2
* [predicate function matches( ) has been introduced in 7.0 EhP 2](https://help.sap.com/doc/abapdocu_740_index_htm/7.40/en-US/index.htm?file=abennews-71-logical_expressions.htm)

I'd say it is a false positive flag.

**Comment by larshp** [comment]
yea, but do 
`ELSEIF matches( val = <ls_token>-str regex = mc_function_open_regex ) = abap_true.`
first, instead of
`ELSEIF matches( val = <ls_token>-str regex = mc_function_open_regex ).`
doing it without the compare is something 740'ish

**Comment by AlexandreHT** [comment]
Compiler refuses ``IF matches( val = <ls_token>-str regex = mc_function_open_regex ) = abap_true.``. 
I am on 740sp6 but considering ABAP legendary backward compatibility, I'm pretty sure it won't work on 740sp2 either.

**Comment by larshp** [comment]
yea, hmm, I've never used the `matches` function, try something like

```abap
IF boolc( matches( val = 'sdf' regex = 'sdf' ) ) = abap_true.
```

**Comment by larshp** [comment]
^its tweaks for 702, linter seemed to be okay with this now that its 702 compatible

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
