### PR TITLE
feat: Check 100 - Downport: No new syntax

### PR DESCRIPTION
**Pull request by mauriciolauffer**
This check helps developers to identify new syntax whenever they need to downport their ABAP code to older ABAP versions (prior to ABAP 7.40).

### CODE REVIEW

**Comment by larshp** [comment]
cool, see errors found by abaplint, https://github.com/larshp/abapOpenChecks/pull/917/checks?check_run_id=431117804

There is a lot of pitfalls, but this is the best we can do with what we have, so lets just try to get it out there :)

**Comment by mauriciolauffer** [comment]
I'm in doubt with the messages such as "_Method parameter name must not match pattern ^R._.*$: error_code_"...
It **must** or **must NOT** match the pattern? Because right now the parameters don't match the pattern, however it still fails and the message says it **MUST NOT**.

**Comment by larshp** [comment]
think the error message is misleading, it must match

abapOpenChecks code uses prefixes

**Comment by mauriciolauffer** [comment]
I've just renamed all parameters to comply with abaplint and it's still failing... It seems the issue is on abaplint itself.

**Comment by g-back** [comment]
you're missing the type of the parameter -> iv_ for variables, is_ for structures, it_ for tables etc

**Comment by larshp** [comment]
welcome to abapOpenChecks as a contributor 🎉 

and check 100 🎉

**Pull request merged**
