### PR TITLE
Updated documentation for CHECK_57

### PR DESCRIPTION
**Pull request by jwigert**
I came across a scenario where I didn't have control of the method signature and still needed to use MESSAGE somehow. Added my work-around to the documentation.

### CODE REVIEW

**Comment by larshp** [comment]
thats a quite evil workaround 😄 

would suggest adding the possibility to add a pseudo comment instead, or add the possibility to exclude certain classes from the check, or use ATC exemptions

**Comment by jwigert** [comment]
Yes, I did feel a bit bad when doing it... 😟 

I'll look into your suggestions instead.

**Comment by larshp** [comment]
See 
https://github.com/larshp/abapOpenChecks/blob/master/src/checks/zcl_aoc_check_40.clas.abap#L170
for an example for the pragma

Something like https://github.com/larshp/abapOpenChecks/blob/master/src/checks/zcl_aoc_check_58.clas.abap can exclude certain methods from the check or https://github.com/larshp/abapOpenChecks/blob/master/src/checks/zcl_aoc_check_26.clas.abap can exclude some tables

**Comment by jwigert** [comment]
Thanks, I tried adding a pseudo comment like this:

```abap
    insert_scimessage(
        iv_code = '001'
        iv_text = 'MESSAGE in global class'(m01)
        iv_pcom = '#EC CI_MESSAGE' ).
```

It is displayed correctly when running the check:

image

But the following row is still flagged with an error:

```abap
MESSAGE x017(crm_archive).                          "#EC CI_MESSAGE
```

Am I missing something, or is it some sort of buffering issue?

**Comment by larshp** [comment]
I dont exactly remember, can you move it to a separate issue, then we can close this PR?

**Comment by jwigert** [comment]
Sure, i created issue #901

**Pull request closed without merging**
